### PR TITLE
Support Go Modules

### PR DESCRIPTION
**Pull request by SamWhited**
Pin the Prometheus version and support Go Modules. Because this package is not versioned, nothing needs to be done other than adding a `go.mod` file. If we want to start versioning this package in the future, we can start adding semver compatible tags to give us something to pin to in other projects that depend on this one.

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by SamWhited** [comment]
@crosbymichael thanks! Since this repo isn't updated often (and not likely to be updated all that often), is there any chance you could tag a `v0.0.1` or similar just to clean up other projects `go.mod` files that depend on this?

**Comment by crosbymichael** [comment]
sure!

**Comment by crosbymichael** [comment]
@SamWhited done https://github.com/docker/go-metrics/releases/tag/v0.0.1

**Pull request merged**
